services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=vatsim
      - DB_PASSWORD=vatsim
      - DB_NAME=vatsim
      - MASTER_API_KEY=${MASTER_API_KEY:-default_master_key}
      - UPDATE_INTERVAL=15
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=vatsim
      - POSTGRES_PASSWORD=vatsim
      - POSTGRES_DB=vatsim
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 